#:schema node_modules/wrangler/config-schema.json
name = "bolt"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-07-01"
pages_build_output_dir = "./build/client"

# Environment variables should be set in Cloudflare dashboard or via wrangler secret
# ANTHROPIC_API_KEY and CLOUDFLARE_API_KEY will be configured separately
